# Gitleaks configuration for ai-service
title = "gitleaks config for ai-service"

[allowlist]
description = "allowlist for ai-service"
paths = [
  # Development scripts that use local passwords
  "scripts/fix-account-ids.js",
  "scripts/import-historic-transactions.js",
  "scripts/check-database-data.js",
  "scripts/complete-setup-and-sync.js",
  "scripts/test-gocardless-encryption.js",
  "scripts/test-gocardless-now.js",
  "scripts/sync-transactions-only.js",
  "scripts/check-gocardless-setup.js",
  "scripts/test-sync-endpoints.js",
  "scripts/check-sync-details.js",
  "scripts/check-accounts-for-import.js",
  "scripts/check-accounts-detailed.js",
  # Test files
  "tests/**",
  "**/*.test.ts",
  "**/*.test.js",
  "**/*.spec.ts",
  "**/*.spec.js"
]

# Allow test/example secrets in specific contexts
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_\-\s]?key|apikey)[\s]*[:=][\s]*['"]([a-zA-Z0-9\-_]{20,})['"]'''
[[rules.allowlist]]
description = "Allow test API keys in test files"
regex = '''test-.*-key|mock-.*-key'''

[[rules]]
id = "jwt-token"
description = "JWT token"
regex = '''eyJ[a-zA-Z0-9_\-]*\.eyJ[a-zA-Z0-9_\-]*\.[a-zA-Z0-9_\-]*'''
[[rules.allowlist]]
description = "Allow example/test JWT tokens"
paths = ["docs/**", "README.md", "*.example"]