version: "3.8"

services:
  # Test if Docker can distinguish between file and directory with dot
  test-dot-file:
    image: alpine:latest
    container_name: test-dot-file
    command: |
      sh -c "
        echo '=== Testing .env.production file ==='
        echo ''
        echo '1. File type check:'
        if [ -f /volume1/docker/ai-service/config/.env.production ]; then
          echo '✓ .env.production is a FILE'
        elif [ -d /volume1/docker/ai-service/config/.env.production ]; then
          echo '✗ .env.production is being seen as a DIRECTORY'
        else
          echo '✗ .env.production does not exist'
        fi
        echo ''
        echo '2. Detailed stat:'
        stat /volume1/docker/ai-service/config/.env.production 2>&1
        echo ''
        echo '3. Directory contents:'
        ls -la /volume1/docker/ai-service/config/
        echo ''
        echo '4. Try reading first line:'
        head -1 /volume1/docker/ai-service/config/.env.production 2>&1
      "
    volumes:
      - /volume1/docker/ai-service/config:/volume1/docker/ai-service/config:ro