version: "3.8"

services:
  # Debug container to check file access
  debug:
    image: alpine:latest
    container_name: ai-service-debug
    command: |
      sh -c "
        echo '=== Debug File Access ==='
        echo 'Checking /volume1/docker/ai-service/config/.env.production'
        echo ''
        echo '1. Directory listing:'
        ls -la /volume1/docker/ai-service/config/ || echo 'Directory not found'
        echo ''
        echo '2. File exists check:'
        if [ -f /volume1/docker/ai-service/config/.env.production ]; then
          echo 'File EXISTS'
          echo 'File permissions:'
          ls -la /volume1/docker/ai-service/config/.env.production
          echo ''
          echo '3. Can read file:'
          head -5 /volume1/docker/ai-service/config/.env.production && echo 'YES - File is readable' || echo 'NO - Cannot read file'
        else
          echo 'File DOES NOT EXIST at expected path'
          echo ''
          echo '3. Checking parent directories:'
          echo '/volume1 contents:'
          ls -la /volume1/ 2>/dev/null || echo 'Cannot access /volume1'
          echo ''
          echo '/volume1/docker contents:'
          ls -la /volume1/docker/ 2>/dev/null || echo 'Cannot access /volume1/docker'
          echo ''
          echo '/volume1/docker/ai-service contents:'
          ls -la /volume1/docker/ai-service/ 2>/dev/null || echo 'Cannot access /volume1/docker/ai-service'
        fi
        echo ''
        echo '=== End Debug ==='
        sleep 60
      "
    volumes:
      - /volume1/docker/ai-service:/volume1/docker/ai-service:ro