version: "3.8"

services:
  # Test container to verify env file loading
  test-env:
    image: alpine:latest
    container_name: ai-service-test-env
    env_file:
      - /volume1/docker/ai-service/config/.env.production
    command: |
      sh -c "
        echo '=== Testing Environment Variables ==='
        echo 'POSTGRES_PASSWORD=' $POSTGRES_PASSWORD
        echo 'TELEGRAM_BOT_TOKEN=' $TELEGRAM_BOT_TOKEN
        echo 'NODE_ENV=' $NODE_ENV
        echo '=== End Test ==='
        env | grep -E 'POSTGRES|TELEGRAM|NODE' | sort
      "
    volumes:
      - /volume1/docker/ai-service/config:/config:ro