version: '3.8'
services:
  ai-service:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - n8n
  n8n:
    image: n8nio/n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=pass
      - N8N_HOST=n8n
      - N8N_PORT=5678
    ports:
      - "5678:5678"
    restart: unless-stopped
