import createClient from 'openapi-fetch';
export { createClient };
import type { paths as AiServicePaths } from './generated/ai-service';
export type { paths as AiServicePaths } from './generated/ai-service';
export const createAiServiceClient = (baseUrl: string) => createClient<AiServicePaths>({ baseUrl });
import type { paths as FinancialPaths } from './generated/financial';
export type { paths as FinancialPaths } from './generated/financial';
export const createFinancialClient = (baseUrl: string) => createClient<FinancialPaths>({ baseUrl });
import type { paths as GatewayPaths } from './generated/gateway';
export type { paths as GatewayPaths } from './generated/gateway';
export const createGatewayClient = (baseUrl: string) => createClient<GatewayPaths>({ baseUrl });
