global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # AI Service metrics
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # PostgreSQL Exporter (if added later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # n8n metrics (if available)
  # - job_name: 'n8n'
  #   static_configs:
  #     - targets: ['n8n:5678']
  #   metrics_path: '/metrics'