name: Contracts Drift Check

on:
  pull_request:
  push:
    branches:
      - main
      - feat/**

jobs:
  contracts-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure pnpm exists before any step that might use pnpm (including setup-node cache)
      - name: Ensure pnpm via Corepack (fallback)
        run: corepack enable && corepack prepare pnpm@10.12.1 --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Remove pnpm cache usage here to avoid requiring pnpm in PATH during this step
          # cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Generate contracts
        run: pnpm contracts:generate

      - name: Build contracts
        run: pnpm contracts:build

      - name: Check for drift
        run: pnpm contracts:check
